<?php

use Grocy\Middleware\JsonMiddleware;
use GrocyAI\Controllers\Api\GrocyAiApiController;
use GrocyAI\Controllers\GrocyAiBulkController;
use GrocyAI\Controllers\GrocyAiCaptureController;
use GrocyAI\Controllers\Api\GrocyAiCaptureResearchController;
use GrocyAI\Controllers\GrocyAiConversionController;
use Slim\Routing\RouteCollectorProxy;

require_once __DIR__ . '/src/GrocyAiDiagnostic.php';
require_once __DIR__ . '/src/GrocyAiContract.php';
require_once __DIR__ . '/src/GrocyAiGtin.php';
require_once __DIR__ . '/src/GrocyAiBarcodeService.php';
require_once __DIR__ . '/src/GrocyAiService.php';
require_once __DIR__ . '/src/GrocyAiTaxonomyMigration.php';
require_once __DIR__ . '/src/GrocyAiInventoryScope.php';
require_once __DIR__ . '/src/GrocyAiTaxonomyService.php';
require_once __DIR__ . '/src/GrocyAiConversionMigration.php';
require_once __DIR__ . '/src/GrocyAiConversionService.php';
require_once __DIR__ . '/src/GrocyAiBulkMigration.php';
require_once __DIR__ . '/src/GrocyAiGroupSuggestionService.php';
require_once __DIR__ . '/src/GrocyAiBulkService.php';
require_once __DIR__ . '/src/GrocyAiCaptureMigration.php';
require_once __DIR__ . '/src/GrocyAiReceiptMigration.php';
require_once __DIR__ . '/src/GrocyAiReceiptImageStore.php';
require_once __DIR__ . '/src/GrocyAiReceiptService.php';
require_once __DIR__ . '/src/GrocyAiReceiptExtractor.php';
require_once __DIR__ . '/src/GrocyAiCaptureResearchMigration.php';
require_once __DIR__ . '/src/GrocyAiCaptureResearchService.php';
require_once __DIR__ . '/src/GrocyAiCaptureService.php';
require_once __DIR__ . '/src/GrocyAiApiController.php';
require_once __DIR__ . '/src/GrocyAiConversionController.php';
require_once __DIR__ . '/src/GrocyAiBulkController.php';
require_once __DIR__ . '/src/GrocyAiCaptureController.php';
require_once __DIR__ . '/src/GrocyAiCaptureResearchController.php';

$app->group('/api/grocy-ai', function (RouteCollectorProxy $group)
{
	$group->get('/status', [GrocyAiApiController::class, 'Status']);
	$group->get('/barcodes/resolve/{barcode}', [GrocyAiApiController::class, 'ResolveBarcode']);
	$group->get('/products/enrich/upc/{upc}', [GrocyAiApiController::class, 'EnrichByUpc']);
	$group->get('/products/{productId}/taxonomy', [GrocyAiApiController::class, 'ProductTaxonomy']);
	$group->put('/products/{productId}/taxonomy', [GrocyAiApiController::class, 'AssignProductTaxonomy']);
	$group->get('/products/{productId}/conversion-status', [GrocyAiApiController::class, 'ProductConversionStatus']);
	$group->get('/conversions/validate', [GrocyAiApiController::class, 'ValidateConversion']);
	$group->get('/conversions/resolved-provenance', [GrocyAiApiController::class, 'ResolvedConversionProvenance']);
	$group->get('/conversions/coverage', [GrocyAiApiController::class, 'ConversionCoverage']);
	$group->post('/bulk/plans', [GrocyAiApiController::class, 'GenerateBulkPlan']);
	$group->get('/bulk/plans/{planId}', [GrocyAiApiController::class, 'BulkPlan']);
	$group->put('/bulk/plans/{planId}/items/{seq}/selection', [GrocyAiApiController::class, 'BulkPlanSetItemSelection']);
	$group->get('/bulk/plans/{planId}/selected-diff', [GrocyAiApiController::class, 'BulkPlanSelectedDiff']);
	$group->post('/bulk/plans/{planId}/apply', [GrocyAiApiController::class, 'BulkPlanApply']);
	$group->get('/bulk/plans/{planId}/audit', [GrocyAiApiController::class, 'BulkPlanAudit']);
	$group->get('/bulk/plans/{planId}/rollback-preview', [GrocyAiApiController::class, 'BulkPlanRollbackPreview']);
	$group->post('/bulk/plans/{planId}/rollback', [GrocyAiApiController::class, 'BulkPlanRollback']);
	$group->get('/bulk/plans/{planId}/export', [GrocyAiApiController::class, 'ExportBulkPlan']);
	$group->get('/bulk/conversion-audit', [GrocyAiApiController::class, 'BulkConversionAudit']);
	$group->get('/capture/trips', [GrocyAiApiController::class, 'ListCaptureTrips']);
	$group->post('/capture/trips', [GrocyAiApiController::class, 'StartCaptureTrip']);
	$group->post('/capture/trips/{tripId}/scan', [GrocyAiApiController::class, 'ScanCaptureTrip']);
	$group->post('/capture/research/jobs/claim', [GrocyAiCaptureResearchController::class, 'Claim']);
	$group->post('/capture/research/jobs/{jobId}/complete', [GrocyAiCaptureResearchController::class, 'Complete']);
	$group->post('/capture/research/jobs/{jobId}/fail', [GrocyAiCaptureResearchController::class, 'Fail']);
	$group->get('/capture/trips/{tripId}', [GrocyAiApiController::class, 'CaptureTrip']);
	$group->put('/capture/trips/{tripId}', [GrocyAiApiController::class, 'UpdateCaptureTrip']);
	$group->put('/capture/trips/{tripId}/lines/{seq}', [GrocyAiApiController::class, 'UpdateCaptureLine']);
	$group->post('/capture/trips/{tripId}/commit', [GrocyAiApiController::class, 'CommitCaptureTrip']);
	$group->post('/capture/trips/{tripId}/cancel', [GrocyAiApiController::class, 'CancelCaptureTrip']);
	$group->get('/capture/trips/{tripId}/receipt-readiness', [GrocyAiApiController::class, 'CaptureReceiptReadiness']);
	$group->post('/capture/trips/{tripId}/receipts', [GrocyAiApiController::class, 'UploadCaptureReceipt']);
	$group->get('/capture/trips/{tripId}/receipts', [GrocyAiApiController::class, 'ListCaptureReceipts']);
	$group->get('/capture/trips/{tripId}/receipts/{receiptId}', [GrocyAiApiController::class, 'CaptureReceipt']);
	$group->get('/capture/trips/{tripId}/receipts/{receiptId}/image', [GrocyAiApiController::class, 'CaptureReceiptImage']);
	$group->post('/capture/trips/{tripId}/receipts/{receiptId}/extract', [GrocyAiApiController::class, 'ExtractCaptureReceipt']);
	$group->post('/capture/trips/{tripId}/receipts/{receiptId}/retry', [GrocyAiApiController::class, 'RetryCaptureReceipt']);
	$group->put('/capture/trips/{tripId}/receipts/{receiptId}', [GrocyAiApiController::class, 'UpdateCaptureReceipt']);
	$group->post('/capture/trips/{tripId}/receipts/{receiptId}/lines', [GrocyAiApiController::class, 'AddCaptureReceiptLine']);
	$group->put('/capture/trips/{tripId}/receipts/{receiptId}/lines/{lineId}', [GrocyAiApiController::class, 'UpdateCaptureReceiptLine']);
	$group->put('/capture/trips/{tripId}/receipts/{receiptId}/lines/{lineId}/allocation', [GrocyAiApiController::class, 'UpdateCaptureReceiptAllocation']);
	$group->get('/capture/trips/{tripId}/receipts/{receiptId}/lines/{lineId}/matches', [GrocyAiApiController::class, 'SuggestCaptureReceiptMatches']);
	$group->post('/capture/trips/{tripId}/receipts/{receiptId}/finish', [GrocyAiApiController::class, 'FinishCaptureReceipt']);
	$group->post('/capture/trips/{tripId}/receipts/{receiptId}/reopen', [GrocyAiApiController::class, 'ReopenCaptureReceipt']);
	$group->get('/images/{variant}/{token}', [GrocyAiApiController::class, 'FetchImage']);
})->add(JsonMiddleware::class);

$app->get('/grocyai/conversioncoverage', [GrocyAiConversionController::class, 'ConversionCoverage']);
$app->get('/grocyai/bulkreview', [GrocyAiBulkController::class, 'BulkReview']);
$app->get('/grocyai/capture', [GrocyAiCaptureController::class, 'Capture']);
$app->get('/grocyai/capture/review', [GrocyAiCaptureController::class, 'Review']);
